// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjJ2_YdxzvBC5Guc8fn9s6dHeXInXR7_Q',
    appId: '1:351435827313:web:f18c67dcda71214d3c53d0',
    messagingSenderId: '351435827313',
    projectId: 'lecturer-appointment-39895',
    authDomain: 'lecturer-appointment-39895.firebaseapp.com',
    storageBucket: 'lecturer-appointment-39895.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_JFXjP279PRDTDEkTUouSiqdhP6QaohM',
    appId: '1:351435827313:android:452eec7ac83a0ebf3c53d0',
    messagingSenderId: '351435827313',
    projectId: 'lecturer-appointment-39895',
    storageBucket: 'lecturer-appointment-39895.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJPYJhi3WMi8P6mGANFbq52l49SYpR8gA',
    appId: '1:351435827313:ios:266e273b1ab9ea733c53d0',
    messagingSenderId: '351435827313',
    projectId: 'lecturer-appointment-39895',
    storageBucket: 'lecturer-appointment-39895.firebasestorage.app',
    iosBundleId: 'com.example.lecturersAppointment',
  );
}
